name: pub_update

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          dart pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage
      
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1