name: ♻️ Sync Labels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/labels.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  labels:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/sync_labels.yml@v1.20.1
